%YAML:1.0		
#此句话不可删除


# camera intrinsics
# camera
camera.cx: 318.1
camera.cy: 258.9
camera.fx: 520.0
camera.fy: 520.0

camera.depth_scale: 1000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 20
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1

scan_frame_num: 100

#WIFI Parameters
SERVER_PORT: 6000
CLIENT_PORT: 7000
SERVER_IP: "192.168.1.102"
CLIENT_IP: "192.168.1.103"
